# Generated by Django 2.2.6 on 2020-04-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('contact_no', models.IntegerField(verbose_name='Contact_No')),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
    ]
